#!/bin/bash
#SBATCH --account=def-srogers
#SBATCH --job-name=BISMARK_GenomePrep
#SBATCH --mail-user=james.bull@ucalgary.ca
#SBATCH --mail-type=ALL
#SBATCH --time=10:00:00
#SBATCH --mem=30G

## Set input and output directories 

ref_coho_dir=~/projects/rrg-srogers/communal/CohoRef_OkisV2

## Load required modules

module purge

module load nixpkgs/16.09
module load gcc/7.3.0
module load bismark/0.22.1

module load bowtie2

# Prep genomes, only once (DONE)

perl $EBROOTBISMARK/bismark_genome_preparation --verbose $ref_coho_dir