#!/bin/bash
#SBATCH --account=def-srogers
#SBATCH --job-name=BISMARK_COHO
#SBATCH --output=slurm-$SLURM_JOBID-BISMARK_COHO
#SBATCH --mail-user=james.bull@ucalgary.ca
#SBATCH --mail-type=ALL
#SBATCH --time=20:00:00
#SBATCH --mem=40G

## Set input and output directories 

inputdir=~/projects/rrg-srogers/jbull/RRBS_Coho_JKB2_mini
ref_coho_dir=~/projects/rrg-srogers/communal/CohoRef_OkisV2

## Load required modules

module purge

module load nixpkgs/16.09
module load gcc/7.3.0
module load bismark/0.22.1

module load bowtie2
module load samtools/1.9

## Copy data to local node (480GB SSD per node)

cp $inputdir/*.trimgalore2.dediversified.1P.fastq.gz $SLURM_TMPDIR
cp $inputdir/*.trimgalore2.dediversified.2P.fastq.gz $SLURM_TMPDIR

## Loop over sample to perform alignment

mkdir $inputdir/5_AlignmentReports

cd $SLURM_TMPDIR

n=1

for i in *.trimgalore2.dediversified.1P.fastq.gz;do

	j=${i%.*.*.*.*.*.*}
	
	echo "starting sample $n id $j"
	
	read1P=$j.UMI.trimgalore2.dediversified.1P.fastq.gz
	read2P=$j.UMI.trimgalore2.dediversified.2P.fastq.gz
	
	## Do alignment of paired reads, in all cases output bam files are sorted to allow merging. Rename and copy back to work directory
	
	perl $EBROOTBISMARK/bismark --genome $ref_coho_dir -1 $read1P -2 $read2P
	
	samtools sort $j.UMI.trimgalore2.dediversified.1P_bismark_bt2_pe.bam -o $j.UMI.trimgalore2.dediversified.1P_bismark_bt2_pe.sorted.bam
		
	mv $j.UMI.trimgalore2.dediversified.1P_bismark_bt2_pe.sorted.bam $j.UMI.trimgalore2.dediversified.PE.bismark.bam
	mv $j.UMI.trimgalore2.dediversified.1P_bismark_bt2_PE_report.txt $j.UMI.trimgalore2.dediversified.PE.bismark_report.txt
	
	cp $j.UMI.trimgalore2.dediversified.PE.bismark.bam $inputdir
	cp $j.UMI.trimgalore2.dediversified.PE.bismark_report.txt $inputdir/5_AlignmentReports

	## Advance counter
	
	n=$(($n+1))
	
done

## Clean up scratch

cd $SLURM_TMPDIR
rm -r *

## Profit!
